# Generated by Django 2.2 on 2021-08-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20210820_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='books_app.User'),
        ),
    ]
